name: Shared Services Apply

on:
  push:
    branches:
      - main
    paths:
      - "*.tf"
      - "terraform.tfvars.example"
      - ".github/workflows/shared-services-plan.yml"
      - ".github/workflows/shared-services-apply.yml"

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: shared-services-production

    env:
      TF_VAR_shared_services_account_id: ${{ secrets.SHARED_SERVICES_ACCOUNT_ID }}
      TF_VAR_sandbox_account_id: ${{ secrets.SANDBOX_ACCOUNT_ID }}
      TF_VAR_tgw_test_account_ids: ${{ vars.TGW_TEST_ACCOUNT_IDS_JSON }}
      TF_VAR_create_tgw_test_instance: ${{ vars.CREATE_TGW_TEST_INSTANCE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials (management gateway OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT_ID }}:role/github-actions-aws-shared-services-infra
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "~> 1.6"

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
